---
title: "R-introduction"
output: html_document
---

### Baisc

---

#### R has five basic or "atomic" classes of objects

- character
- numeric (real numbers)
- integer
- complex
- logic (True/False)

#### The most baisc object is vector

- A vector and only contain objects of the same class.
- BUT: The one exception is list, which represent a vector but can contain objects of different classes(indeed, that's usually why we use them)

#### Numbers in R a generally treated as numeric objects

```R
> typeof(1)
[1] "double"
> typeof(1L)
[1] "integer"
```

#### Attributes

- names, dimnames
- dimensions
- class
- length
- other user-defined attributes/metadata 

Attributes of object can be accessed using the attributes() function.

### Creating vectors

---

#### the c() function:

```R
x <- c(0.5, 0.6)
y <- c(TRUE, FALSE)
z <- c(T, F)
a <- c('a', 'b', 'c')
b <- 9:20
c <- c(1+0i, 2+4i)
```

#### using the vector() function

```R
x <- vector("numeric", length=10)
```

#### Mixing Object

```R
> x <- c(1.7, 'a') 
> typeof(x)
[1] "character"
> x <- c(TRUE, 2)
> typeof(x)
[1] "double"
> x <- c('a', TRUE)
> typeof(x)
[1] "character"
```

#### Explicit Coerction

```R
> x <- 0:6
> as.logical(x)
[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
> as.numeric(x)
[1] 0 1 2 3 4 5 6
> as.character(x)
[1] "0" "1" "2" "3" "4" "5" "6"
> as.complex(x)
[1] 0+0i 1+0i 2+0i 3+0i 4+0i 5+0i 6+0i
```

#### Nonsensical coercion results NAs.

```R
> x <- c('a', 'b', 'c')
> as.numeric(x)
[1] NA NA NA
警告信息：
强制改变过程中产生了NA 
> as.logical(x)
[1] NA NA NA
> as.complex(x)
[1] NA NA NA
警告信息：
强制改变过程中产生了NA 
```

### Lists

```R
> x <- list('a' ,1 , TRUE, '1+4i')
> x
[[1]]
[1] "a"

[[2]]
[1] 1

[[3]]
[1] TRUE

[[4]]
[1] "1+4i"
```

### Matrix

Matrices are vectors with a dimension attribute. The dimension is itsefl an integer vector of length 2(nrow, ncol)

```R
> x <- matrix()
> x
     [,1]
[1,]   NA
>
> x <- matrix(nrow = 2, ncol = 3)
> x
     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA
> dim(x)
[1] 2 3
> attributes(x)
$dim
[1] 2 3

```

Add dimension to matrix or vector

```R
> m <- 1:6
> m
[1] 1 2 3 4 5 6
> dim(m)
NULL
> dim(m) <- c(2,3)
> m
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
> dim(m)
[1] 2 3
```

cbind-ing and rbind-ing

```R
> m <- 1:3
> n <- 7:9
> rbind(m,n)
  [,1] [,2] [,3]
m    1    2    3
n    7    8    9
> cbind(m,n)
     m n
[1,] 1 7
[2,] 2 8
[3,] 3 9
```
