---
title: "Loop Function"
author: "Dong Zhou"
date: "01/24/2016"
output: html_document
---


#### lapply

- The lapply() function takes a list as input, applies a function to each element of the list, then returns a list of the same length as the original one.
- The 'l' in 'lapply' stands for 'list'.

```R
cls_list <- lapply(flags, class)
```

```R
x <- list(a=1:5, b=rnorm(10), c=rnorm(20,1), c=rnorm(100,5))
lapply(x, mean)
```

```R
$a
[1] 3
$b
[1] 0.3057864
$c
[1] 0.6914496
$c
[1] 5.133292
```

#### sapply

1. result <- lapply()
2. as.character(result)

In general, if the result is a list where every element is of length one, then sapply() returns a vector. If the result is a list where every element is a vector of the same length (> 1), sapply() returns a matrix. If sapply() can't figure things out, then it just returns a list, no different from what lapply() would give you.

#### apply

```R
> x <- matrix(1:16, 4, 4)
> x
     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16
```

```R
> apply(x, 1, mean)
[1]  7  8  9 10
```

```R
> mean(x[1,])
[1] 7
> mean(x[2,])
[1] 8
> mean(x[3,])
[1] 9
> mean(x[4,])
[1] 10
```

#### mapply

```R
 mapply(rep, 1:4, 4:1)
[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4
```

vapply() and tapply(), each of which serves a very specific purpose within the Split-Apply-Combine methodology

#### vapply

- Whereas sapply() tries to 'guess' the correct format of the result, vapply() allows you to specify it explicitly. If the result doesn't match the format you specify, vapply() will throw an error, causing the operation to stop. This can prevent significant problems in your code that might be caused by getting unexpected return values from sapply().

- You might think of vapply() as being 'safer' than sapply(), since it requires you to specify the format of the output in advance, instead of just allowing R to 'guess' what you wanted. In addition, vapply() may perform faster than sapply() for large datasets. However, when doing data analysis interactively (at the prompt), sapply() saves you some typing and will often be good enough.

#### tapply

- As a data analyst, you'll often wish to split your data up into groups based on the value of some variable, then apply a function to the members of each group. The next function we'll look at, tapply(), does exactly that.
- Use tapply() to split your data into groups based on the value of some variable, then apply a function to each group.

- Take a vector or other objects and split into groups determined by a factor or list of factors.
